apiVersion: v1
kind: pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app

sepc:
  containers:
    - name:
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
